version: "3.9"

services:
  etcd-1:
    container_name: etcd1
    hostname: etcd1
    restart: always
    image: quay.io/coreos/etcd:v3.5.1
    networks:
      - default
    entrypoint: /usr/local/bin/etcd
    command:
      - --name=etcd-1
      - --initial-advertise-peer-urls=http://etcd-1:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://etcd-1:2379
      - --initial-cluster-token=mys3cr3ttok3n
      - --heartbeat-interval=250
      - --election-timeout=1250
      - --initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380
      - --initial-cluster-state=new
      - --data-dir=/etcd_data
    ports:
      - 2379:2379
    volumes:
      - ${VOLUME_PREFIX}/etcd/etcd1:/etcd_data
  etcd-2:
    container_name: etcd2
    hostname: etcd2
    restart: always
    image: quay.io/coreos/etcd:v3.5.1
    networks:
      - default
    entrypoint: /usr/local/bin/etcd
    command:
      - --name=etcd-2
      - --initial-advertise-peer-urls=http://etcd-2:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://etcd-2:2379
      - --initial-cluster-token=mys3cr3ttok3n
      - --heartbeat-interval=250
      - --election-timeout=1250
      - --initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380
      - --initial-cluster-state=new
      - --data-dir=/etcd_data
    ports:
      - 2380:2379
    volumes:
      - ${VOLUME_PREFIX}/etcd/etcd2:/etcd_data
  etcd-3:
    container_name: etcd3
    hostname: etcd3
    restart: always
    image: quay.io/coreos/etcd:v3.5.1
    networks:
      - default
    entrypoint: /usr/local/bin/etcd
    command:
      - --name=etcd-3
      - --initial-advertise-peer-urls=http://etcd-3:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://etcd-3:2379
      - --initial-cluster-token=mys3cr3ttok3n
      - --heartbeat-interval=250
      - --election-timeout=1250
      - --initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380
      - --initial-cluster-state=new
      - --data-dir=/etcd_data
    ports:
      - 2381:2379
    volumes:
      - ${VOLUME_PREFIX}/etcd/etcd3:/etcd_data
networks:
  default:
    external:
      name: ${DOCKER_NETWORK:-webproxy}
